# version: 2.1
# orbs:
#   node: circleci/node@5.0.1
#   docker: circleci/docker@2.1.4
# jobs:
#   build:
#     docker:
#       - image: cimg/node:16.10
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: npm
#       - run: |
#           echo "Installing dependencies..."
#           npm install
#   test:
#     docker:
#       - image: cimg/node:16.10
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: npm
#       - run: |
#           echo "Running tests..."
#           npm run test
#   build-and-push:
#     executor: docker/docker
#     steps:
#       - setup_remote_docker
#       - checkout
#       - docker/check
#       - docker/build:
#           image: joelchua2403/education-space
#           tag: 0.1.0
#       - docker/push:
#           image: joelchua2403/education-space
#           tag: 0.1.0

# workflows:
#   simple_workflow:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#       - build-and-push:
#           requires:
#             - test

# With Heroku deployment

# version: 2.1
# orbs:
#   node: circleci/node@5.0.1
#   docker: circleci/docker@2.1.4
#   heroku: circleci/heroku@2.0.0
# jobs:
#   build:
#     docker:
#       - image: cimg/node:16.10
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: npm
#       - run: |
#           echo "Installing dependencies..."
#           npm install
#   test:
#     docker:
#       - image: cimg/node:16.10
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: npm
#       - run: |
#           echo "Running tests..."
#           npm run test
#   build-and-push:
#     executor: docker/docker
#     steps:
#       - setup_remote_docker
#       - checkout
#       - docker/check
#       - docker/build:
#           image: joelchua2403/education-space
#           tag: 0.1.0
#       - docker/push:
#           image: joelchua2403/education-space
#           tag: 0.1.0
#   deploy:
#     docker:
#         - image: cimg/node:16.10
#     steps:
#         - setup_remote_docker      
#         - heroku/install
#         - checkout
#         - run:
#             name: Heroku Container Push
#             command: | 
#                 heroku container:login
#                 heroku container:push web -a joelchua-devops
#                 heroku container:release web -a joelchua-devops

# workflows:
#   simple_workflow:
#     jobs:
#       - build
#           filters:
#             branches:
#               only: main
#       - test:
#           requires:
#             - build
#           filters:
#             branches:
#               only: main  #filter by branch
#       - build-and-push:
#           requires:
#             - test
#       - deploy:
#           requires:
#             - build-and-push
#           filters:
#             tags:
#               only: /^\d+\.\d+\.\d+$/  #filter by tags semenatic versioning





version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  scan:
    docker:
        - image: cimg/node:16.10
    environment:
        IMAGE_NAME: joelchua2403/education-space
    steps:
        - checkout
        - setup_remote_docker      
        - docker/check
        - run: docker build -t joelchua2403/educationspace .
        - snyk/scan: 
            docker-image-name: joelchua2403/educationspace

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - scan:
          requires:
            - build