version: 2.1
orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.2.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

  push:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker:
          version: 20.10.8
      - checkout
      - run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
      - run: docker build -t nodeappfordevops .
      - run: docker push nodeappfordevops
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - push:
          requires:
            - test
          filters:
            branches:
              only: main
